baseurl = "https://fdd.kawayi.moe"
DefaultContentLanguage = "zh-cn"
title = "反到底"
theme = "beautifulhugo"

publishDir = "docs"

[Params]
  homeTitle = "反到底online"
  subtitle = "¡反到底在行动!"
  mainSections = ["post","posts"]
  logo = "mstile-150x150.png" # Expecting square dimensions
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = false
  disclaimerText = "以上纯属作者观点,和反到底无关"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  # name = "F"
  website = "fdd.kawayi.moe"
  email = "fdd@kawayi.moe"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
